pipeline {
    agent any
	def mvnHome = tool 'M3'

    stages {
        stage('checkout') {
            steps {
               git url : 'https://github.com/GJohannes/baJenkins'
            }
        }
        stage('Build') {
           	agent {
				label "maven-3.5-jdk-8"
             }
             steps {
             	sh "mvn -version
             	sh "{mvnHome}/bin/mvn compile"
             	
             }
        }
    }
}