pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
               git url : 'https://github.com/GJohannes/baJenkins'
            }
        }
        stage('Build') {
           	agent {
				label "maven-3.5-jdk-8"
             }
             steps {
             	sh "mvn -version"
             }
        }
    }
}